# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Samon/Downloads/绩效目标审核.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5 import uic
from qt_material import apply_stylesheet
import pandas as pd
from jixiao import jixiao,deordered2list,ordered2text
from ui_jx import Ui_MainWindow
from ui import  PandasModel


class jixiaoshenhe(QMainWindow,jixiao):

    def __init__(self):
        super().__init__()
        self.bianma = None
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.pushButton.clicked.connect(self.open_folder)
        self.ui.pushButton_2.clicked.connect(self.shenhe_inited)
        self.ui.pushButton_3.clicked.connect(self.excelWrite)
        self.ui.pushButton_3.clicked.connect(self.update_plus_num)
        self.ui.pushButton_4.clicked.connect(self.excelWrite)
        self.ui.pushButton_4.clicked.connect(self.update_minus_num)

    def open_folder(self):
        # 使用 QFileDialog.getExistingDirectory() 方法打开文件夹选择对话框
        folder = QFileDialog.getExistingDirectory(self,'选择文件夹')
        self.read_item(folder)

    def update_plus_num(self):
        self.num += 1
        self.bianma = self.bianma_list[self.num]
        self.display()

    def update_minus_num(self):
        self.num -= 1
        self.bianma = self.bianma_list[self.num]
        self.display()

    def shenhe_inited(self):
        self.shenhe_init()
        self.ui.bianma_box.addItems(self.bianma_list)
        self.shenhe()
        self.bianma = self.bianma_list[0]
        self.display()
        self.rengongshenhe()

    def rengongshenhe(self):
        self.ui.comboBox_2.addItems(list(self.shenhe_muban.loc[self.shenhe_muban["审核要点"]=="完整性","审核细项"]))
        self.ui.comboBox_3.addItems(list(self.shenhe_muban.loc[self.shenhe_muban["审核要点"]=="可测性","审核细项"]))
        self.ui.comboBox_4.addItems(list(self.shenhe_muban.loc[self.shenhe_muban["审核要点"]=="可行性","审核细项"]))
        self.shenhe_dict = self.shenhe_dict.set_index("审核细项")["审核意见表述（问题+建议）"].to_dict()
        self.ui.comboBox_2.activated.connect(self.handle_item_changed_wanzheng)
        self.ui.comboBox_3.activated.connect(self.handle_item_changed_kece)
        self.ui.comboBox_4.activated.connect(self.handle_item_changed_kexing)

    def handle_item_changed_wanzheng(self, index):
        self.ui.wanzheng_listWidget.addItem(self.shenhe_dict[self.ui.comboBox_2.itemText(index)])

    def handle_item_changed_kece(self, index):
        self.ui.kecexing_listwidget.addItem(self.shenhe_dict[self.ui.comboBox_3.itemText(index)])

    def handle_item_changed_kexing(self, index):
        self.ui.kexingxing_listwidget.addItem(self.shenhe_dict[self.ui.comboBox_4.itemText(index)])

    def display(self):
        zhengceyiju = self.data_unit()['政策依据'].values[0]
        cesuanyiju = self.data_unit()['测算依据'].values[0]
        niandumubiao = self.data_unit()['年度目标'].values[0]
        model = PandasModel(self.data_unit()[["二级指标","三级指标","指标值","指标解释"]])
        self.ui.zhengceyiju.setText(zhengceyiju)
        self.ui.cesuanyiju.setText(cesuanyiju)
        self.ui.niandumubiao.setText(niandumubiao)
        self.ui.jixiaozhibiao_tableview.setModel(model)
        self.ui.jixiaozhibiao_tableview.resizeRowsToContents()
        self.ui.wanzheng_listWidget.clear()
        self.item_wanzheng_shenhe_list = deordered2list(self.shenhe_info.loc[self.shenhe_info['项目编码']==self.bianma,"完整性审核"].values[0])
        self.ui.wanzheng_listWidget.addItems(self.item_wanzheng_shenhe_list)
        # self.ui.wanzheng_listWidget.setSelectionMode(QListWidget.itemDoubleClicked)
        # self.ui.wanzheng_listWidget.setEditTriggers(QListWidget.itemDoubleClicked)
        # self.ui.wanzheng_listWidget.itemChanged.connect(self.handle_item_changed)
        # self.ui.wanzheng_listWidget.itemDoubleClicked.connect(self.handle_editing_finished)
        self.ui.kecexing_listwidget.clear()
        self.ui.kecexing_listwidget.addItems(deordered2list(self.shenhe_info.loc[self.shenhe_info['项目编码']==self.bianma,"可测性审核"].values[0]))
        self.ui.kexingxing_listwidget.clear()
        self.ui.kexingxing_listwidget.addItems(deordered2list(self.shenhe_info.loc[self.shenhe_info['项目编码']==self.bianma,"可行性审核"].values[0]))
        self.ui.summary_view.clear()
        self.ui.summary_view.addItems(deordered2list(self.shenhe_info.loc[self.shenhe_info['项目编码']==self.bianma,"初审小结"].values[0]))


    def excelWrite(self):
        wanzhengyijian = ordered2text(list(self.ui.wanzheng_listWidget.all_item()))
        keceyijian = ordered2text(list(self.ui.kecexing_listwidget.all_item()))
        kexingyijian = ordered2text(list(self.ui.kexingxing_listwidget.all_item()))
        self.shenhe_info.loc[self.shenhe_info['项目编码']==self.bianma,"完整性审核"] = wanzhengyijian
        self.shenhe_info.loc[self.shenhe_info['项目编码']==self.bianma,"可测性审核"] = keceyijian
        self.shenhe_info.loc[self.shenhe_info['项目编码']==self.bianma,"可行性审核"] = kexingyijian
        self.shenhe_info.to_excel("./初审结果.xlsx",sheet_name="人工审核")

if __name__ == '__main__':

    app = QApplication(sys.argv)
    apply_stylesheet(app, theme='light_cyan_500.xml')
    w = jixiaoshenhe()
    # w.setupUi(MainWindow)
    #w.display()
    w.show()
    sys.exit(app.exec_())
